### ISSUE TITLE
Final Project Individual Report

### ISSUE THREAD

**Issue by michaelweylandt** [jasonamey/STA9750-2024-FALL#7]
Hi Jason, 

Where is the link for your final project individual report? I've got the group report from @clintavarghese 's page. 

Thanks

**Comment by jasonamey** [comment]
I had created a repo just for the code for the project and opened an issue
there :
https://github.com/jasonamey/park-slope-west-property-analysis

[image: Screenshot 2024-12-26 at 12.12.45 PM.jpg]

My individual report would be here:
https://jasonamey.github.io/STA9750-2024-FALL/individual_report.html

**Comment by michaelweylandt** [comment]
Gotcha - thanks.
